# Generated by Django 6.1 on 2026-08-14 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('manage_catalog', 'Kann den Strafenkatalog verwalten')],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_penalties', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='people.person')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_penalties', to=settings.AUTH_USER_MODEL)),
                ('catalog_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='penalties.penaltycatalogentry')),
            ],
            options={
                'ordering': ['-issued_at'],
                'permissions': [('issue_penalty', 'Kann Strafen aussprechen'), ('remove_penalty', 'Kann Strafen löschen'), ('mark_penalty_paid', 'Kann Strafen als bezahlt markieren')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_payments', to=settings.AUTH_USER_MODEL)),
                ('penalties', models.ManyToManyField(related_name='payments', to='penalties.penalty')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('issued', 'Ausgesprochen'), ('paid', 'Bezahlt'), ('removed', 'Entfernt'), ('amount_changed', 'Betrag geändert')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_events', to=settings.AUTH_USER_MODEL)),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='penalties.penalty')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
