# Generated by Django 6.1 on 2026-08-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
