# Generated by Django 6.1 on 2026-08-09 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0003_penaltyevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-issued_at']},
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='paid_by',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalty_payments', to=settings.AUTH_USER_MODEL)),
                ('penalties', models.ManyToManyField(related_name='payments', to='penalties.penalty')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
