# Generated by Django 6.1 on 2026-08-09 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0004_alter_penalty_options_remove_penalty_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-issued_at'], 'permissions': [('issue_penalty', 'Kann Strafen aussprechen'), ('remove_penalty', 'Kann Strafen löschen'), ('mark_penalty_paid', 'Kann Strafen als bezahlt markieren')]},
        ),
    ]
