# Generated by Django 6.1 on 2026-08-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0006_penalty_removed_at_penalty_removed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltyevent',
            name='new_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='penaltyevent',
            name='previous_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='penaltyevent',
            name='event_type',
            field=models.CharField(choices=[('issued', 'Ausgesprochen'), ('paid', 'Bezahlt'), ('removed', 'Entfernt'), ('amount_changed', 'Betrag geändert')], max_length=32),
        ),
    ]
