# Generated by Django 6.1 on 2026-08-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0007_penaltyevent_new_amount_penaltyevent_previous_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penaltyevent',
            options={'ordering': ['created_at'], 'permissions': [('manage_catalog', 'Kann Strafen verwalten')]},
        ),
    ]
