# Generated by Django 6.1 on 2026-08-10 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penalties', '0008_alter_penaltyevent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penaltyevent',
            options={'ordering': ['created_at']},
        ),
    ]
