# Generated by Django 6.1 on 2026-08-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('manage_person', 'Kann Personen verwalten')]},
        ),
    ]
